name: Upload assets on new Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: grafeasgroup/actions-poetry@v1.0.0
        with:
          args: install
      - name: Build wheel
        uses: grafeasgroup/actions-poetry@v1.0.0
        with:
          args: run poetry build

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: dist/*.whl
